### ISSUE TITLE
UnboundLocalError: ...goose_extractor...

### ISSUE THREAD

**Issue by benradford** [openeventdata/scraper#75]
Traceback:
```
bitnami@ubuntu14-generic-template-01:~/scraper$ sudo python scraper.py
Scraper is running 2015-06-28 15:45:29
Running. See log file for further information.
english
english
english
english
english
english
Traceback (most recent call last):
  File "scraper.py", line 404, in <module>
    run_scraper()
  File "scraper.py", line 399, in run_scraper
    auth_pass, db_host=db_host)
  File "scraper.py", line 314, in call_scrape_func
    [r.get(9999999) for r in results]
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
UnboundLocalError: local variable 'goose_extractor' referenced before assignment
```

System info:
```
Linux version 3.13.0-45-generic (buildd@phianna) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 26
Stepping:              4
CPU MHz:               2899.999
BogoMIPS:              5799.99
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0,1
```

**Comment by benradford** [comment]
Suspected user error. Will double check and update soon.

**Comment by benradford** [comment]
If you get this error, make sure all of your *feedburner* links have *?format=xml* at the end.
